//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDescuento
    {
        public int idDetalleDescuento { get; set; }
        public int idDescuento { get; set; }
        public int idMedicamento { get; set; }
    
        public virtual Descuento Descuento { get; set; }
        public virtual Medicamento Medicamento { get; set; }
    }
}
