//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamento()
        {
            this.DetalleDescuentoes = new HashSet<DetalleDescuento>();
            this.Kardexes = new HashSet<Kardex>();
        }
    
        public int idMedicamento { get; set; }
        public int idCategoria { get; set; }
        public string nombreMedicamento { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fechaVencimiento { get; set; }
        public Nullable<decimal> precioCompra { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public Nullable<int> numLote { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDescuento> DetalleDescuentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kardex> Kardexes { get; set; }
    }
}
